/* Generated by Yosys 0.27+22 (git sha1 53c0a6b78, clang 11.0.1-2 -fPIC -Os) */

//module wave(clk, dataout);
module wave(
  input [7:0] io_in,
  output [7:0] io_out
);
  wire [4:0] _0_;
  wire [31:0] _1_;
  wire _2_;
  wire [4:0] _3_;
  reg [4:0] _4_ = 5'h00;
  reg [5:0] _5_ = 6'h00;
  wire [179:0] _6_;
  wire [5:0] _7_;
//  input clk;
//  wire clk;
  wire clk = io_in[0];
  wire [5:0] conv;
  wire [6:0] conv2;
//  output [6:0] dataout;
  wire [6:0] dataout;
  wire [4:0] i;
  wire [179:0] sine;
  assign io_out[6:0] = dataout;
  reg [5:0] \27  [29:0];
  initial begin
    \27 [0] = 6'h19;
    \27 [1] = 6'h13;
    \27 [2] = 6'h0d;
    \27 [3] = 6'h08;
    \27 [4] = 6'h04;
    \27 [5] = 6'h02;
    \27 [6] = 6'h00;
    \27 [7] = 6'h00;
    \27 [8] = 6'h02;
    \27 [9] = 6'h04;
    \27 [10] = 6'h08;
    \27 [11] = 6'h0d;
    \27 [12] = 6'h13;
    \27 [13] = 6'h19;
    \27 [14] = 6'h20;
    \27 [15] = 6'h26;
    \27 [16] = 6'h2c;
    \27 [17] = 6'h32;
    \27 [18] = 6'h37;
    \27 [19] = 6'h3b;
    \27 [20] = 6'h3d;
    \27 [21] = 6'h3f;
    \27 [22] = 6'h3f;
    \27 [23] = 6'h3d;
    \27 [24] = 6'h3b;
    \27 [25] = 6'h37;
    \27 [26] = 6'h32;
    \27 [27] = 6'h2c;
    \27 [28] = 6'h26;
    \27 [29] = 6'h20;
  end
  assign _7_ = \27 [_0_];
  assign _1_ = { 27'h0000000, i } + 32'd1;
  assign _2_ = { 27'h0000000, i } == 32'd29;
  assign _3_ = _2_ ? 5'h00 : _1_[4:0];
  always @(posedge clk)
    _4_ <= _3_;
  always @(posedge clk)
    _5_ <= _7_;
  assign _0_ = 5'h1d - i;
  assign i = _4_;
  assign conv = _5_;
  assign conv2 = { 1'h0, conv };
  assign sine = 180'h826b32dfbf7fffdef7cac9a065334810200008420d4d9;
  assign dataout = conv2;
endmodule
